-- Explore customers countries
SELECT DISTINCT country 
FROM dim_customers


-- Explore all categories 
SELECT DISTINCT category, subcategory, product_name 
FROM dim_products


-- Count distinct products 
SELECT COUNT(DISTINCT product_name) AS product_number
FROM dim_products


-- Earliest and latest dates 
SELECT 
	MIN(order_date) AS ealier_date, 
	MAX(order_date) AS last_order_date,
	DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS order_years_range
FROM fact_sales


-- Yougest and oldest customer
SELECT  
	MAX(birthdate) AS yougest_birthday, 
	DATEDIFF(YEAR,MAX(birthdate),CURRENT_DATE) AS yougest_old,
	MIN(birthdate) AS oldest_birthday,
	DATEDIFF(YEAR,MIN(birthdate),CURRENT_DATE) AS oldest_old
FROM dim_customers


-- Total sales
SELECT SUM(sales_amount) AS total_sales FROM fact_sales


-- Quantity of sold items 
SELECT SUM(quantity) AS total_quantity FROM fact_sales


-- Average of selling price
SELECT AVG(price) AS avg_price FROM fact_sales


-- Total number of orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM fact_sales


-- Total number of products
SELECT COUNT(DISTINCT product_id) AS total_product FROM dim_products


-- Total number of customers
SELECT COUNT(DISTINCT customer_id) AS total_customer FROM dim_customers

-- Total number of customers who placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customer_order FROM fact_sales


-- Report of all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM fact_sales
UNION ALL 
SELECT 'Average Price', AVG(price) FROM fact_sales
UNION ALL 
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM fact_sales
UNION ALL
SELECT 'Total product', COUNT(DISTINCT product_id) FROM dim_products
UNION ALL
SELECT 'Total customer', COUNT(DISTINCT customer_id) AS total_customer FROM dim_customers
UNION ALL
SELECT 'Total customer who ordered', COUNT(DISTINCT customer_key) AS total_customer_order FROM fact_sales



-- Total customers by counstries
SELECT 
	country,
	COUNT(DISTINCT customer_id) AS total_customers 
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC


-- Total customer by gender
SELECT 
	gender, 
	COUNT(customer_id) AS total_customers 
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC


-- Total products by category
SELECT 
	category,
	COUNT(product_number) AS total_product 
FROM dim_products
GROUP BY category
ORDER BY total_product DESC


-- Average cost in each category
SELECT 
	category, 
	AVG(cost) AS average_cost 
FROM dim_products
GROUP BY category
ORDER BY average_cost DESC


-- Total revenue generated by each category
SELECT p.category, 
	SUM(f.sales_amount) AS revenue
FROM fact_sales AS f
LEFT JOIN dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY revenue DESC


-- Total revenue generated by each customer
SELECT 
	c.first_name,
	c.last_name,
	c.customer_number, 
	SUM(sales_amount) AS revenue
FROM fact_sales AS f 
LEFT JOIN dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.customer_number,c.first_name,c.last_name
ORDER BY revenue DESC


-- Distribution of sold items across countries
SELECT 
	c.country,
	SUM(f.quantity) AS total_sold
FROM fact_sales AS f 
LEFT JOIN dim_customers AS c
ON f.customer_key = c.customer_key 
GROUP BY c.country
ORDER BY total_sold DESC


-- Top 5 products that genereate the highest revenue 
SELECT * 
FROM (
	SELECT p.product_name, 
	SUM(f.sales_amount) AS revenue,
	RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS product_rank
	FROM fact_sales AS f
	LEFT JOIN dim_products AS p
	ON p.product_key = f.product_key
	GROUP BY p.product_name) AS t
WHERE product_rank <= 5


-- The 5 worst-performing products in terms of sales 
SELECT TOP 5 p.product_name, 
	SUM(f.sales_amount) AS revenue
FROM fact_sales AS f
LEFT JOIN dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY revenue 


-- Top 5 best subcategories
SELECT TOP 5 p.subcategory, 
	SUM(f.sales_amount) AS revenue
FROM fact_sales AS f
LEFT JOIN dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY revenue DESC
